from abc import ABCMeta


class RestfulStatusConsts(metaclass=ABCMeta):
    STATUS_OK = 200
    STATUS_HANDLING_FAILED = 202
    STATUS_TYPE_ERROR = 300
    STATUS_NOT_IN_ENUM = 302
    STATUS_EXPIRED_TOKEN = 303
    STATUS_INVALID_TOKEN = 304
    STATUS_BAD_PARAMETER = 305
    STATUS_BAD_FORM_DATA = 306
    STATUS_UNAUTHORIZED = 401
    STATUS_FORBIDDEN = 403
    STATUS_NOT_FOUND = 404
    STATUS_METHOD_NOT_ALLOWED = 405
    STATUS_INTERNAL_SERVER_ERROR = 500
